// zeliboba - boot key provisioning.
//
// The CMeP first loader verifies the staged second loader with a 2048-bit RSA key
// that on real hardware lives in the CMeP key table at 0xE0066000. That table is
// part of the chip and is not present in any dump available to us, so without it
// the loader's `img_proc_5C798` can never pass and the honest boot chain stops
// there.
//
// To keep every real code path running we provision the emulated hardware with a
// *development* key (see bootkeys_data.h, generated by tools/make_boot_keys.py)
// and re-sign the staged payload with the matching private key. The loader still
// performs the exponentiation on the emulated Bignum engine and still memcmps the
// result against its own ROM constants - nothing about the loader is bypassed.
//
// This is documented in docs/KBL.md; pass --no-provision to leave the emulated
// key table empty (the loader then fails exactly as it does with an unprovisioned
// console).
#pragma once

#include <string>
#include <vector>

#include "bus/bus.h"
#include "common/types.h"

namespace zlb {

/// Where the loader expects the modulus table and its selector strap.
namespace bootkey_addrs {
constexpr u32 kKeyTable = 0xE0066000;   ///< 0x5C832: 0xE0060000 | (0x6000)
constexpr u32 kStrap = 0xE0064060;      ///< 0x5C804: read at 0x5C808
constexpr u32 kDigestInfo = 0x5E774;    ///< 18 bytes compared at 0x5C888
constexpr u32 kTailKey = 0x5E744;       ///< keyring 0x20 key material (0x5C7B0)
constexpr u32 kExpectedHead = 0x5E764;  ///< the exponent stream source
constexpr size_t kSignatureOffset = 0x1C0;   ///< image + 0xE0 + 0xE0
constexpr size_t kDigestTableOffset = 0x1A0; ///< 0x5C958: image+0xE0+0xC0
constexpr size_t kPayloadOffset = 0x2C0;     ///< 0x5CC30: image + 0x2C0
}  // namespace bootkey_addrs

/// Seed the CMeP key table, select the key-table boot path and re-sign `image`
/// (the staged SLB2 `second_loader.enp` payload) in place.
///
/// `cmep_bus` must already hold the first loader at 0x5C000 so that the ROM
/// constants can be read back and checked. Returns false with `why` filled in
/// when the fitted loader is a different build than the one this key was made
/// for - in that case nothing is modified.
bool provision_boot_keys(Bus& cmep_bus, std::vector<u8>& image, std::string& why);

/// Describe what provisioning would do without changing anything.
std::string describe_boot_keys(Bus& cmep_bus, const std::vector<u8>& image = {});

}  // namespace zlb
