#!/usr/bin/env python3
"""Generate src/debug/nid_table_data.cpp from vita_loader's NID database.

The database lives in the pup_fiction checkout (../pup_fiction/vita_loader/db.yml
relative to this repository).  It maps module -> library -> function -> NID, which
is exactly what is needed to put names on the NIDs the emulator sees while it walks
a guest's import tables.

Usage:
    python3 tools/gen_nid_table.py [path/to/db.yml] [-o src/debug/nid_table_data.cpp]

The generated file is pure data; the lookups live in src/debug/nid_table.cpp.
"""

from __future__ import annotations

import argparse
import os
import sys

try:
    import yaml
except ImportError:  # pragma: no cover - the checkout has PyYAML
    sys.exit("PyYAML is required: pip install pyyaml")


HEADER = '''// Generated by tools/gen_nid_table.py - do not edit by hand.
//
// Source: pup_fiction/vita_loader/db.yml (module -> library -> function -> NID).
// The database is tagged firmware {firmware}; the NIDs themselves are ABI hashes
// and are shared across firmware revisions, so a 1.04 guest resolves as well.  Any
// NID that is absent simply prints as a bare hex value.
//
// {entries} functions, {modules} modules, {libraries} libraries.

#include "debug/nid_table.h"

namespace zlb::debug {

namespace {

const NidEntry kNidEntries[] = {
'''


def escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "db",
        nargs="?",
        default="../pup_fiction/vita_loader/db.yml",
        help="path to vita_loader's db.yml",
    )
    parser.add_argument("-o", "--output", default="src/debug/nid_table_data.cpp")
    args = parser.parse_args()

    if not os.path.exists(args.db):
        sys.exit(f"database not found: {args.db}")

    with open(args.db, "r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle)

    modules = data.get("modules") or {}
    firmware = str(data.get("firmware", "unknown"))

    rows = []
    for module_name, module in modules.items():
        for library_name, library in (module.get("libraries") or {}).items():
            for function_name, nid in (library.get("functions") or {}).items():
                if not isinstance(nid, int):
                    continue
                rows.append((nid & 0xFFFFFFFF, function_name, library_name, module_name))

    rows.sort(key=lambda row: (row[0], row[2], row[1], row[3]))
    unique = len({row[0] for row in rows})

    header = HEADER
    for token, value in (
        ("{firmware}", firmware),
        ("{entries}", str(len(rows))),
        ("{modules}", str(len(modules))),
        ("{libraries}", str(sum(len(m.get("libraries") or {}) for m in modules.values()))),
    ):
        header = header.replace(token, value)
    lines = [header]
    for nid, function_name, library_name, module_name in rows:
        lines.append(
            '    {0x%08Xu, "%s", "%s", "%s"},\n'
            % (nid, escape(function_name), escape(library_name), escape(module_name))
        )
    lines.append("};\n\n")
    lines.append("}  // namespace\n\n")
    lines.append("const NidEntry* nid_entries() { return kNidEntries; }\n\n")
    lines.append("std::size_t nid_entry_count() { return sizeof(kNidEntries) / sizeof(kNidEntries[0]); }\n\n")
    lines.append("}  // namespace zlb::debug\n")

    with open(args.output, "w", encoding="utf-8", newline="\n") as handle:
        handle.writelines(lines)

    print(
        "wrote %s: %d entries (%d unique NIDs), %d modules, firmware %s"
        % (args.output, len(rows), unique, len(modules), firmware)
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
